# Generated by Django 5.1.1 on 2024-10-01 09:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qflapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('since', models.CharField(blank=True, max_length=4, null=True)),
                ('designation', models.CharField(blank=True, choices=[('Patron', 'Patron'), ('Vice-Patron', 'Vice-Patron')], max_length=50, null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
