# Generated by Django 5.1.1 on 2024-10-08 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qflapp', '0005_book_alter_person_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='file_id',
            field=models.CharField(default='default_link', max_length=100),
            preserve_default=False,
        ),
    ]
