# Generated by Django 5.1.1 on 2024-10-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qflapp', '0006_book_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
